// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/create-profile": {
    params: {};
  };
  "/user-profile": {
    params: {};
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/create-profile" | "/user-profile" | "/profile";
  };
  "containers/Landing.tsx": {
    id: "containers/Landing";
    page: "/";
  };
  "containers/Login.tsx": {
    id: "containers/Login";
    page: "/login";
  };
  "containers/CreateProfile.tsx": {
    id: "containers/CreateProfile";
    page: "/create-profile";
  };
  "containers/ProfileSummary.tsx": {
    id: "containers/ProfileSummary";
    page: "/user-profile";
  };
  "containers/Profile.tsx": {
    id: "containers/Profile";
    page: "/profile";
  };
};